responses =  {
    "user_da_ton_tai":"User already exists",
    "email_da_duoc_dang_ky":"Email is already in use, please try another email",
    "email_chua_duoc_dang_ky":"Email is not registered, please enter your correct registered email",
    "mat_khau_khong_dung":"Password is wrong",
    "co_loi_xay_ra":"Some thing wrong , pls try again",
    "check_email_to_get_code":"Check email to get code ",
    "dang_ky_thanh_cong":"Sign Up Success",
    "dang_ky_that_bai":"Registration failed",
    "code_bi_qua_thoi_gian":"Code is expired",
    "dang_nhap_thanh_cong":"Logged in successfully",
    "sai_mat_khau":"Wrong password",
    "tai_khoan_chua_duoc_dang_ky":"Account is not registered",
    "cap_nhat_mat_khau_moi_thanh_cong":"New password updated successfully",
    "sai_code":"Wrong code",
    "cam_on_dong_gop_cua_ban":"Thank you for your contribution",
    "sua_thong_tin_thanh_cong":"Information processing successfully",
    "booking_tour_thanh_cong":"Tour booking successful",
    "booking_tour_that_bai":"Tour booking failed",
    "thoi_gian_nay_ban_dang_lua_chon_tour_du_lich_khac_roi":"This time you have chosen a different tour",
    "ban_chua_dang_ky_tour_du_lich_nao":"You have not registered for any tour yet",
    "tour_du_lich_da_duoc_xoa_thanh_cong":"Your tour has been successfully deleted",
    "tour_da_het_thoi_gian_de_xoa":"The tour has timed out so it can be deleted"
}